name: Deploy to Eswatini Facts Website

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Deploy to FTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local_path: ./website/*
        remote_path: ./
          
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Website should be available at: http://eswatinifacts.org/"
        echo "Checking if website is accessible..."
        curl -I http://eswatinifacts.org/ || echo "Website may still be propagating"